apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vulnerability-agent
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: agent
            image: eu.gcr.io/ptcs-docker-registry/container-vulnerability-agent-k8s:master-5
            args:
             - --scannerApi:http://1.2.3.4
             - --apiKey:keyhere
             - --collectGceInfo
          restartPolicy: Never
