apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vulnerability-agent
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: agent
            image: ptcos/container-vulnerability-agent-k8s
            args:
             - --scannerApi:http://1.2.3.4
             - --auth:'user:pass'
             - --collectGceInfo
          restartPolicy: Never
