apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vulnerability-agent
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: agent
            image: ptcos/container-vulnerability-agent-k8s
            args:
            - --help
          restartPolicy: Never